#!/data/data/com.termux/files/usr/bin/sh
PATH=$HOME/bin:$PATH

out=$HOME/last.url
echo "$1" > $out

cat $out

printf '\n\n\n\n\nLabel this for ~~SHORT_LINK_SITE~~? [] '
read label

if [ -z "$label" ]; then 
	# -F multipart form
    curl \
    ~~CGI_BASTION_AUTH~~ \
    -F u="$1" \
      https://~~CGI_BASTION_SITE~~/termux-dest/urlsave.cgi
else
    u=$(echo "$1" | sed 's/%/%25/g;s/&/%26/g')
	# -d regular form
    curl \
    ~~SHORT_LINK_AUTH~~ \
    -d label="$label" -d url="$u" \
      https://config.~~SHORT_LINK_SITE~~/new.topping \
    > $out.json

    if grep -q 'status.*okay' $out.json ; then
	n="https://$label.~~SHORT_LINK_SITE~~/"
	echo $n |pbset
	echo $n
        rm $out.json
    fi
fi

echo Also stored in $out
